Feature branch
tahiry-dev/bubble-sort pull request #1
Opened 2020-10-08 14:42 UTC by tahiry-dev

Bubble sort is an algorithm that compares adjacent values and swaps them if necessary. 
Our project uses:  
- Variables
- Conditional Statements
- Functions
- Loops 
- Blocks
- Yield

2020-10-08 15:26 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish all the requirements , you required to do these changes, listed below:
- [ ] Please fix linter issues
- [ ] Elaborate README file, follow this [example file](https://github.com/TSHEPO-CLOUD/bubble_sort/tree/feature_branch#bubble_sort)

### Summary

-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-10-08 15:26 UTC, bertil291utn commented on bubble_main.rb
> +end
## Sort by

- Check this method

```ruby
unsorted=(1..10).to_a.reverse! 
%w[hi hey hello].bubble_sort_by(unsorted) { |left, right| left.length - right.length }
# => expected: ["hi", "hey", "hello"]
# => got: ["hi", "hello", "hey"]
     
```

2020-10-09 09:24 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO :wave: NICE WORK DOING THE CHANGES AS REQUESTED BY THE PREVIOUS TSE. HOWEVER, THERE IS STILL A PROBLEM IN ONE OF YOUR METHODS KINDLY CHECK BELOW :arrow_down: 

### IF YOU HAVE ANY QUESTION REACH ME ON SLACK @PETERROBERT

### HAPPY CODING :computer:

2020-10-09 09:24 UTC, peterrobert commented on bubble_main.rb
> +end
There is still a problem with this method kindly check below


`
       expected: ["hi", "hey", "hello"]
            got: ["hi", "hello", "hey"]
     `
### hint: kindly double check the implementation in your block

2020-10-09 12:39 UTC, maelfosso approved these changes
# Congratulations :clap: 

Well done job :smile: 
You can merge it now :+1: 

Good continuation :handshake: 

Mael FOSSO

2020-10-09 16:03 UTC, merged